name: kinachat
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 2.0.0
  flutter_svg:
  lottie: 1.4.1
  get: 4.6.5
  get_storage: 
  draggable_fab: ^0.1.4
  connectivity_plus: ^2.3.8
  flutter_easyloading: ^3.0.3
  flutter_spinkit: 
  animate_do: ^2.1.0
  http:
  sqflite: ^2.2.0+3
  google_sign_in: ^5.4.2
  optimized_cached_image: ^3.0.1
  flutter_launcher_icons:
  flutter_isolate: ^2.0.4
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/vectors/
    - assets/svgs/
    - assets/lotties/
    - assets/cats/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DidactGothic
      fonts:
        - asset: assets/fonts/DidactGothic-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
